### ISSUE TITLE
Setup file for install on Mac OSX

### ISSUE THREAD

**Issue by victorbs** [compmem/ptsa#3]
I had to add a couple of lines to get the install.py script to work. I needed to
import numpy

and

include_dirs = [numpy.get_include()]

See below for the full file:

from distutils.core import setup, Extension
from distutils.sysconfig import get_config_var
from distutils.extension import Extension

import os
import sys
import numpy

# get the version loaded as vstr
execfile('ptsa/versionString.py')

# set up extensions
ext_modules = []
edf_ext = Extension("ptsa.data.edf.edf",
                    include_dirs = [numpy.get_include()],
                    sources = ["ptsa/data/edf/edf.c",
                               "ptsa/data/edf/edfwrap.c",
                               "ptsa/data/edf/edflib.c"],
                    define_macros = [('_LARGEFILE64_SOURCE', None),
                                     ('_LARGEFILE_SOURCE', None)],)
ext_modules.append(edf_ext)

# define the setup
setup(name='ptsa', 
      version=vstr, 
      maintainer=['Per B. Sederberg'],
      maintainer_email=['psederberg@gmail.com'],
      url=['http://ptsa.sourceforge.net'],
      packages=['ptsa','ptsa.tests','ptsa.data','ptsa.data.tests',
                'ptsa.data.edf','ptsa.plotting','ptsa.plotting.tests',
                'dimarray','dimarray.tests'],
      ext_modules = ext_modules
      )

**Comment by psederberg** [comment]
Thanks for pointing this out. We have updated the setup.py to reflect these changes.
